### ISSUE TITLE
the script for running the math benchmark

### ISSUE THREAD

**Issue by darkpromise98** [ECNU-ICALK/EduChat-Math#2]
A great math benchmark for MLLM evaluation!  I want to add the benchmark for my own model, could you please provide the script for running the benchmark?

**Comment by DrJZhou** [comment]
Sure, we have released the evaluation codes in this project.

**Comment by darkpromise98** [comment]
Thanks! 

What's more, the number of images in `Images/All_Images` is about 13000+, but the number of images for total datasets is 15000+. Why is there a inconsistent statement in the number of images.

**Comment by Y-PanC** [comment]
Thank you for your attention! Because there are cases where the same image needs to be inserted multiple times, we calculate the number of image insertions, not the number of images.
