### ISSUE TITLE
请问能提供shot的推理代码吗？

### ISSUE THREAD

**Issue by fuqianya** [ECNU-ICALK/EduChat-Math#5]
您好，我看到论文中使用3-shot后，推理性能有提升。
但是repo中没有相关的代码，论文中也没有相关的阐述。您能提供更多的信息吗？

**Comment by Y-PanC** [comment]
好的，稍后会上传更多的代码，谢谢您的关注，请多多支持我们的工作！

**Comment by yucheng-zzhao** [comment]
HI，了解下什么时间计划上传这块代码呀 @Y-PanC
