### ISSUE TITLE
The number of evaluation datasets is Different with the number of  the model output

### ISSUE THREAD

**Issue by Mengqing1993** [ECNU-ICALK/EduChat-Math#7]
We can see the number of evaluation datasets is 5,821 in paper.
But in the github project ,the model output length is 3,581. like ./outputs/closed-source/gemini_common.jsonl
Why is these number is different?
What is the actual dataset that you used in evaluation?

**Comment by Y-PanC** [comment]
Thank you for your attention! The version you downloaded should be the original version, and this issue was fixed five days ago. I just checked it again and there should be no problem. Please download it again.

**Comment by Mengqing1993** [comment]
Thanks!!
